# Generated by Django 3.0.3 on 2020-02-05 11:06

from django.db import migrations


class Migration(migrations.Migration):
    def insert_data(apps, schema_editor):
        Role = apps.get_model('main', 'Roles')
        role = Role(name="admin")
        role.save()
        role = Role(name="editor")
        role.save()
        role = Role(name="viewer")
        role.save()

    dependencies = [
        ('main', '0002_auto_20200203_1229'),
    ]

    operations = [
        migrations.RunPython(insert_data),
    ]
