# Generated by Django 3.0.3 on 2020-02-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200203_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
