# Generated by Django 3.0.3 on 2020-02-07 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200207_1208'),
        ('main', '0004_auto_20200207_1156'),
    ]

    operations = [
    ]
