# Generated by Django 3.0.3 on 2020-02-21 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200219_1325'),
        ('main', '0014_auto_20200219_1418'),
    ]

    operations = [
    ]
