# Generated by Django 3.0.3 on 2020-02-24 11:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_merge_20200221_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
