# Generated by Django 3.0.3 on 2020-03-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200309_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
