# Generated by Django 3.0.3 on 2020-03-10 13:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_items_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='order',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
