# Generated by Django 3.0.3 on 2020-03-10 13:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20200310_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elements',
            name='order',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
