# Generated by Django 3.0.3 on 2020-03-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20200310_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
