# Generated by Django 3.0.3 on 2020-03-10 13:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20200310_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='order',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='elements',
            name='order',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
    ]
